# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Authelia
version: "0.1"
slug: example
description: Authelia add-on
arch:
  - amd64
init: false
map:
  - share:rw
image: 'authelia/authelia'
