name: "MeTube"
description: "A YouTube music downloader"
version: "1.0.0"
slug: "metube"
arch:
  - amd64
  - armv7
url: https://github.com/alexta69/metube/pkgs/container/metube
map:
  - config: rw
  - share: rw
image: "ghcr.io/home-assistant/metube"
init: false
#ingress: true
#ingress_port: 8081
#ingress_stream: true
startup: application
#boot: auto
ports:
  8081/tcp: 8081
ports_description:
  8081/tcp: "MeTube Web Port"
#volumes:
#  - /share/youtube_music:/downloads
#webui: http://[HOST]:[PORT:8081]
#watchdog: tcp://[HOST]:[PORT:8081]
