name: "MeTube
description: "A YouTube music downloader"
version: "1.0.0"
slug: "metube"
arch:
  - amd64
  - arm64
url: https://github.com/alexta69/metube/pkgs/container/metube
map:
  - config:r
  - share:rw
image: ghcr.io/alexta69/metube
init: false
ingress: true
legacy: true
video: true
ingress_port: 8081
ingress_stream: true
startup: application
#boot: auto
ports:
  8081/tcp: 8081
ports_description:
  8081/tcp: "MeTube Web Port"
volumes:
  - /share/youtube_music:/downloads
webui: http://[HOST]:8081
watchdog: tcp://[HOST]:[PORT:8081]
