name: "MeTube"
version: "1.0.0"
slug: "metube"
description: "A web-based YouTube downloader"
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
#boot: "auto"
ports:
  8081/tcp: 8081
#options: {}
#schema: {}
map:
#  - homeassistant_config
  - media
  - share
